###  Installing and Using Pandas

In [4]:
# ! pip install pandas

In [2]:
pd.__version__

'2.1.4'

In [3]:
pd?

Type:        module
String form: <module 'pandas' from 'c:\\Users\\hp\\anaconda3\\Lib\\site-packages\\pandas\\__init__.py'>
File:        c:\users\hp\anaconda3\lib\site-packages\pandas\__init__.py
Docstring:
pandas - a powerful data analysis and manipulation library for Python
=====================================================================

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a set of labels, or the user can simply ignore the labels and let
    `Series`, `DataFrame`, etc. automatically align the data for you in
    computations.
  - Powerful, flexible group by functionality to perform split-apply-combine
    operations on data sets, for both aggregating and transforming data.
  - Make it easy to convert ragged, differently-indexed data in other Python
    and NumPy data structures into DataFrame objects.
  - Intelligent label-based slicing, fancy indexing, and subsetting of large
    data sets.
  - Intuitive merging and joining data sets.
  - Flexible reshaping and pivoting of data sets.
  - Hierarchical labeling of axes (possible to have multiple labels per tick).
  - Robust IO tools for loading data from flat files (CSV and delimited),
    Excel files, databases, and saving/loading data from the ultrafast HDF5
    format.
  - Time series-specific functionality: date range generation and frequency
    conversion, moving window statistics, date shifting and lagging.

### Introducing Pandas Objects

In [2]:
import numpy as np
import pandas as pd

####  The Pandas Series Object

In [8]:
data =pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [16]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [17]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [20]:
print(data[0],'\n',
      data[2:])

0.25
 2    0.75
3    1.00
dtype: float64

####  Series as generalized NumPy array

In [21]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [22]:
data['a']

0.25

In [8]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

####  Series as specialized dictionary

In [6]:
population_dict = {'California': 38332521,
 'Texas': 26448193,
 'New York': 19651127,
 'Florida': 19552860,
 'Illinois': 12882135}

population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [26]:
population['Texas']

26448193

In [31]:
population['Texas':'Florida']

Texas       26448193
New York    19651127
Florida     19552860
dtype: int64

####  Constructing Series objects

In [9]:
# constructing a Pandas Series from list or np.array
pd.Series(data)
pd.Series([1,2,4,5,6])

0    1
1    2
2    4
3    5
4    6
dtype: int64

In [33]:
# data can be a scalar
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [36]:
# data can be dict
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [38]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

####  The Pandas DataFrame Object

#####  DataFrame as a generalized NumPy array

In [10]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
 'Florida': 170312, 'Illinois': 149995}

area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [11]:
df = pd.DataFrame({'population': population,
 'area': area})
df

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [45]:
df.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [46]:
df.columns

Index(['population', 'area'], dtype='object')

In [47]:
df.to_numpy()

array([[38332521,   423967],
       [26448193,   695662],
       [19651127,   141297],
       [19552860,   170312],
       [12882135,   149995]], dtype=int64)

In [13]:
df.describe()

         population           area
count  5.000000e+00       5.000000
mean   2.337337e+07  316246.600000
std    9.640386e+06  242437.411951
min    1.288214e+07  141297.000000
25%    1.955286e+07  149995.000000
50%    1.965113e+07  170312.000000
75%    2.644819e+07  423967.000000
max    3.833252e+07  695662.000000

In [15]:
print(f'col :{df.columns}')
print(f'index {df.index}')

col :Index(['population', 'area'], dtype='object')
index Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

#####  DataFrame as specialized dictionary

In [16]:
df['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

##### Constructing DataFrame objects

**A Pandas DataFrame can be constructed in a variety of ways. Here we’ll give several
 examples.**

#### From a single Series object.

In [29]:
pd.DataFrame(population,columns=['population'])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

#####  From a list of dicts.

In [31]:
dicts = [{"a":i,"b":i*2 ,'c': i *3} for i in range(5)]
pd.DataFrame(dicts)

   a  b   c
0  0  0   0
1  1  2   3
2  2  4   6
3  3  6   9
4  4  8  12

**Even if some keys in the dictionary are missing, Pandas will fill them in with NaN (i.e.,
 “not a number”)**

In [ ]:
pd.DataFrame([{'a': 1, 'b': 2}, {'b': 3, 'c': 4}])

     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

###  The Pandas Index Object

In [35]:
ind = pd.Index([1,2,3,4,5])
ind

Index([1, 2, 3, 4, 5], dtype='int64')

####  Index as immutable array

In [40]:
print(ind[1],ind[2:],ind[::2])

2 Index([3, 4, 5], dtype='int64') Index([1, 3, 5], dtype='int64')

In [41]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64

**One difference between Index objects and NumPy arrays is that indices are immuta
ble—that is, they cannot be modified via the normal means:**

In [42]:
ind[1] = 100

TypeError: Index does not support mutable operations

####  Index as ordered set

In [3]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [58]:
indA & indB # wrong

Index([0, 3, 5, 7, 9], dtype='int64')

In [54]:
indA.intersection(indB) # correct

Index([3, 5, 7], dtype='int64')

In [4]:
indA | indB # wrong

Index([3, 3, 5, 7, 11], dtype='int64')

In [6]:
indA.union(indB) # correct

Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [46]:
indA ^ indB # wrong

Index([3, 0, 0, 0, 2], dtype='int64')

In [5]:
indA.difference(indB) # correct

Index([1, 9], dtype='int64')